services:

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:11.2.0
    attach: false
    container_name: grafana
    restart: unless-stopped
    network_mode: host
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/usr/share/grafana/custom/
    environment:
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_SECURITY_ADMIN_PASSWORD=demo

volumes:
  grafana-storage:
