services:

  # Windows to install the windows_exporter with IIS-collector
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      LANGUAGE: "German"
      REGION: "de-DE"
      KEYBOARD: "de-DE"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - windows-storage:/storage
      - ./windows/:/oem  # post-installation script

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus-windows
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus-windows.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.2.0
    attach: false
    container_name: grafana-windows
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/usr/share/grafana/custom/
      - ./grafana/dashboards:/usr/share/grafana/public/dashboards
    environment:
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_SECURITY_ADMIN_PASSWORD=demo

volumes:
  grafana-storage:
  windows-storage:
