services:

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/usr/share/grafana/custom/
    environment:
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_SECURITY_ADMIN_PASSWORD=demo

volumes:
  grafana-storage:
