services:

  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    restart: unless-stopped
    networks: [ grafana-shared ]
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    extra_hosts:
      - local:host-gateway # access local node exporter

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox-exporter
    restart: unless-stopped
    networks: [ grafana-shared ]
    ports:
      - 9115:9115
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml

  filestat-exporter:
    image: mdoubez/filestat_exporter
    container_name: filestat-exporter
    restart: unless-stopped
    networks: [ grafana-shared ]
    command: [ "-path.cwd", "/exporter/data", "-config.file", "/exporter/filestat.yml" ]
    ports:
      - 9943:9943
    volumes:
      - ./grafana:/exporter/data # for example, track all files in the folder grafana
      - ./filestat.yml:/exporter/filestat.yml

  grafana:
    image: grafana/grafana:11.2.0
    attach: false
    container_name: grafana
    restart: unless-stopped
    networks: [ grafana-shared ]
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/usr/share/grafana/custom/
      - ./grafana/dashboards:/usr/share/grafana/public/dashboards
    environment:
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_SECURITY_ADMIN_PASSWORD=demo

volumes:
  grafana-storage:

# Has to be created manually beforehand via `docker network create grafana-shared`
networks:
  grafana-shared:
    external: true
