apiVersion: 1
datasources:
  - orgId: 1
    name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    editable: true
    url: http://host.docker.internal:9090 # change to localhost in Linux
